relativeURLs = true
baseURL  = "https://github.com/andytirunesh/andu.github.io/"
title    = "Andu Berha"
shortbio = "PhD Candidate, University of Alberta · Consultant, World Bank · Doctoral Fellow, CAPI"
logo     = "profile.jpg"   # put your headshot at content/profile.jpg

theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Associate Professor of Business and Economics, University of California, Berkeley"
    logo = "Rao_headshot_berkeley.jpg" 
    
